version: '2.1'
services:

###############################
   cassandra0:
    image: cassandra
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199:7199
    networks:
     db_net:
      ipv4_address: 172.21.0.2

###############################
   cassandra1:
    image: cassandra
    container_name: cassandra1
    ports:
     - 9142:9042
    networks:
     db_net:
      ipv4_address: 172.21.0.3
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed

###############################
   cassandra2:
    image: cassandra
    container_name: cassandra2
    ports:
     - 9242:9042
    networks:
     db_net:
      ipv4_address: 172.21.0.4
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed
networks:
  db_net:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 172.21.0.0/24
